version: "3"
services:
  config-server:
    build: ./config-server
    ports:
      - "8071:8071"
  licensing-service:
    build: ./licensing-service
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"