# stage 1
FROM arm64v8/gradle:7-jdk11 AS builder
WORKDIR /home/root/app/
COPY . .
RUN gradle build -x test

# stage 2
FROM openjdk:11-jdk-slim
WORKDIR /app
ARG BUILD_DIR=/home/root/app/build/libs
COPY --from=builder ${BUILD_DIR}/*.jar app.jar
ENTRYPOINT ["java", "-jar", "/app/app.jar"]