spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8071

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: true