spring:
  application:
    name: organization-service
  config:
    import: configserver:http://localhost:8071
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: prometheus

logging:
  level:
    com.bakigoal: DEBUG